# Generated by Django 2.2.7 on 2019-12-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='internetInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Elminación')),
                ('device', models.CharField(max_length=80, verbose_name='Nombre del equipo')),
                ('port', models.CharField(max_length=100, verbose_name='Puerto')),
                ('gbpsrx', models.FloatField(verbose_name='Gbps RX')),
                ('gbpstx', models.FloatField(verbose_name='Gbps TX')),
                ('gbpsmax', models.FloatField(verbose_name='Gbps MAX')),
                ('utilization', models.FloatField(verbose_name='Utilización')),
                ('increase', models.FloatField(null=True, verbose_name='Crecimiento')),
                ('solutionTime', models.DateField(null=True, verbose_name='Fecha de Solución')),
                ('comment', models.TextField(null=True, verbose_name='Comentarios')),
                ('deviceIndex', models.CharField(max_length=100, verbose_name='Equipo_Puerto')),
                ('nameServices', models.ManyToManyField(to='api_ppm.Service')),
                ('peerType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ppm.PeerType')),
            ],
        ),
        migrations.CreateModel(
            name='coreInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Estatus')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateField(auto_now=True, verbose_name='Fecha de Elminación')),
                ('device', models.CharField(max_length=80, verbose_name='Nombre del equipo')),
                ('port', models.CharField(max_length=100, verbose_name='Puerto')),
                ('gbpsrx', models.FloatField(verbose_name='Gbps RX')),
                ('gbpstx', models.FloatField(verbose_name='Gbps TX')),
                ('gbpsmax', models.FloatField(verbose_name='Gbps MAX')),
                ('utilization', models.FloatField(verbose_name='Utilización')),
                ('increase', models.FloatField(null=True, verbose_name='Crecimiento')),
                ('solutionTime', models.DateField(null=True, verbose_name='Fecha de Solución')),
                ('comment', models.TextField(null=True, verbose_name='Comentarios')),
                ('deviceIndex', models.CharField(max_length=100, verbose_name='Equipo_Puerto')),
                ('nameServices', models.ManyToManyField(to='api_ppm.Service')),
                ('serviceType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_ppm.ServiceType')),
            ],
        ),
    ]
