# Generated by Django 2.2.7 on 2019-12-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0002_internetip'),
    ]

    operations = [
        migrations.CreateModel(
            name='coreIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
