# Generated by Django 2.2.7 on 2019-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0003_coreip'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetinterface',
            name='capacityInterface',
            field=models.IntegerField(default='0', verbose_name='Capacidad'),
        ),
    ]
