# Generated by Django 2.2.7 on 2019-12-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0004_internetinterface_capacityinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetinterface',
            name='bpsTime',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
