# Generated by Django 2.2.7 on 2019-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0006_auto_20191220_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetinterface',
            name='capacityInterface',
            field=models.FloatField(default='0', verbose_name='Capacidad'),
        ),
    ]
