# Generated by Django 2.2.7 on 2019-12-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0007_auto_20191220_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetinterface',
            name='utilizationrx',
            field=models.FloatField(default='0', verbose_name='Utilización RX'),
        ),
        migrations.AddField(
            model_name='internetinterface',
            name='utilizationtx',
            field=models.FloatField(default='0', verbose_name='Utilización TX'),
        ),
        migrations.AlterField(
            model_name='internetinterface',
            name='utilization',
            field=models.FloatField(default='0', verbose_name='Utilización'),
        ),
    ]
