# Generated by Django 2.2.7 on 2019-12-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0009_auto_20191221_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetinterface',
            options={},
        ),
    ]
