# Generated by Django 2.2.7 on 2019-12-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0011_auto_20191221_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreinterface',
            name='device',
            field=models.CharField(max_length=100, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='coreinterface',
            name='deviceIndex',
            field=models.CharField(max_length=200, verbose_name='Equipo_Puerto'),
        ),
        migrations.AlterField(
            model_name='coreinterface',
            name='port',
            field=models.CharField(max_length=200, verbose_name='Puerto'),
        ),
        migrations.AlterField(
            model_name='internetinterface',
            name='device',
            field=models.CharField(max_length=100, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='internetinterface',
            name='deviceIndex',
            field=models.CharField(max_length=200, verbose_name='Equipo_Puerto'),
        ),
        migrations.AlterField(
            model_name='internetinterface',
            name='port',
            field=models.CharField(max_length=200, verbose_name='Puerto'),
        ),
    ]
