# Generated by Django 2.2.7 on 2019-12-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0012_auto_20191222_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreinterface',
            name='bpsTime',
            field=models.DateTimeField(null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='coreinterface',
            name='capacityInterface',
            field=models.FloatField(default='0', verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='coreinterface',
            name='utilizationrx',
            field=models.FloatField(default='0', verbose_name='Utilización RX'),
        ),
        migrations.AddField(
            model_name='coreinterface',
            name='utilizationtx',
            field=models.FloatField(default='0', verbose_name='Utilización TX'),
        ),
        migrations.AlterField(
            model_name='coreinterface',
            name='utilization',
            field=models.FloatField(default='0', verbose_name='Utilización'),
        ),
    ]
