# Generated by Django 3.0.2 on 2020-01-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ppm', '0013_auto_20191222_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreinterface',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='internetinterface',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
